<a href="https://colab.research.google.com/github/eliyanto29/Hobi-Data-Youtube-Channel/blob/main/Matriks_Dengan_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

![alt text](https://drive.google.com/uc?id=1LorCyNhtayK1l-T8eoHdPLo53NJMgUy-
)

Assalamualaikum warahmatullahi wabarakatuh.

***Robbi Zidni Ilma Warzuqni Fahma***

Semoga Allah memberi kemudahan untuk kita memperoleh ilmu yang bermanfaat.

## **Hasil Yang Ingin Dicapai**
1. Memahami representasi array pada python
2. Mengenal dan memahami representasi matriks pada python
3. Mengenal dan memahami oeprasi matriks pada python
4. Mengenal dan memahami modul linear algebra pada python numpy
5. Membuat matriks menggunakan perulangan pada python

### ***!!!***

***Sebelum memulai mempelajari notebook ini, jangan lupa untuk menyalinnya di drive masing-masing ya.***

### ***!!!***


# **Array dan Operasinya**



**List sebagai Array**

Sebagai catatan penting adalah Python tidak memiliki dukungan bawaan untuk Array, tetapi List Python dapat digunakan sebagai gantinya.

Kita menggunakan konsep **list** sebagai **array**, untuk bekerja dengan array pada Python kita memerlukan untuk mengimpor library numpy.

In [ ]:
import numpy as np

Contoh: Membuat array berisi nama-nama buah:

In [ ]:
buah=['nangka', 'manggis', 'ceplukan', 'mengkudu']
buah

['nangka', 'manggis', 'ceplukan', 'mengkudu']

Array merupakan sebuah variabel yang menyimpan lebih dari 1 buah data yang memiliki tipe data yang sama. Jadi dapat dikatakan bahwa array merupakan kumpulan dari data-data tunggal yang dijadikan dalam 1 variabel array yang alamat memorinya berbeda yang selanjutnya disebut elemen-elemen array yang bisa kita akses berdasarkan indeks.

Sebagai contoh, jika kita memiliki list nama-nama buah sebagai contohnya kita dapat menyimpan nama-nama tersebut dalam variabel tunggal, maka akan terlihat seperti ini: 

In [ ]:
buah1= "nangka"
buah2= "manggis"
buah3= "ceplukan"

Lau, bagaimana jika kita ingin menyimpan nama-nama buah yang sangat banya, 3000 misalnya.

Solusinya adalah array


**Mengakses elemen suatu Array**

Python mengenal slicing operator [ ] yang dapat melakukan ekstraksi sebuah item atau beberapa item yang berada dalam range tertentu pada suatu array. Beberapa tipe urutan juga mendukung "extended slicing" dengan parameter ketiga berupa "step".

* x[0] artinya mengambil elemen paling awal, dengan  index 0 dari array x.

* x[5] artinya mengambil elemen dengan index 5 dari array x.

* x[-1] artinya mengambil elemen dengan index paling belakang ke-1 dari array x.

* x[3:5] artinya membuat array dari anggota elemen array x dengan index 3 hingga sebelum index 5 (tidak termasuk elemen dengan index 5, dalam hal ini hanya index 3-4).

* x[:5] artinya membuat array dari anggota elemen array x paling awal hingga sebelum index 5 (tidak termasuk elemen dengan index 5, dalam hal ini hanya index 0-4).

* x[-3:] artinya membuat array dari anggota elemen array x mulai index ke-3 dari belakang hingga paling belakang.

* x[1:7:2] artinya membuat array dari anggota elemen array x dengan index 1 hingga sebelum index 7, dengan "step" 2 (dalam hal ini hanya index 1, 3, 5).



In [ ]:
x = [5,10,15,20,25,30,35,40]
print(x[5])
print(x[-1])
print(x[3:5])
print(x[:5])
print(x[-3:])
print(x[1:7:2])

30
40
[20, 25]
[5, 10, 15, 20, 25]
[30, 35, 40]
[10, 20, 30]


**Panjang dan dimensi Array**

Gunakan metode len () untuk menentukan panjang array (jumlah elemen dalam array).

In [ ]:
x = len(buah)
x

4

In [ ]:
y= np.shape(buah)
y

(4,)

In [ ]:
A = np.array([[1, 2, 3], [4, 5, 6]])
u = np.shape(A)
u

(2, 3)

**Array dengan Arrange**

In [ ]:
C=np.arange(1,11,2)
C

array([1, 3, 5, 7, 9])

**Perulangan pada Elemen Array**

In [ ]:
for afif in C:
  print(afif)

1
3
5
7
9


**Menambah Elemen Array**

Kita bisa menggunakan metode append() untuk menambahkan elemen ke array.

In [ ]:
buah

['nangka', 'manggis', 'ceplukan', 'mengkudu']

In [ ]:
buah.append("belimbing")
buah

['nangka', 'manggis', 'ceplukan', 'mengkudu', 'belimbing']

**Menghapus Elemen Array**

Anda bisa menggunakan metode pop() atau remove() untuk menghapus elemen dari array.

In [ ]:
buah=['nangka', 'manggis', 'ceplukan', 'mengkudu']
buah

['nangka', 'manggis', 'ceplukan', 'mengkudu']

In [ ]:
# Menghapus elemen kedua pada array buah
# pop() menghapus berdasarkan indeks array
buah.pop(1)
buah

['nangka', 'ceplukan', 'mengkudu']

In [ ]:
# Menghapus elemen kedua pada array buah
# remove() menghapus berdasarkan elemen array
buah.remove('ceplukan')
buah

['nangka', 'mengkudu']

**Build in methods terkait dengan array Python**

| Method | Deskripsi|
--- | --- |
append()| Menambahkan elemen di akhir array
clear() | Menghapus semua elemen dari array
copy()  | Menghasilkan salinan array
count() | Menghitung jumlah elemen dengan nilai yang ditentukan
extend()| Tambahkan elemen daftar (atau iterable), di akhir list
index() | Menghasilkan indeks elemen pertama dengan nilai yang ditentukan
insert() |  Menambahkan elemen pada posisi yang ditentukan
reverse() | Membalik urutan array
sort()  | Mengurutkan array



# **Representasi Matriks Pada Python**

Matriks adalah array 2 dimensi khusus yang mempertahankan sifat 2 dimensinnya melalui operasi. Matriks memiliki operator khusus tertentu, seperti perkalian matriks dan pemangkatan matriks.

Untuk mendefinisikan suatu array dan menggunakan fungsi-fungsi operasi matriks, kita akan menggunakan modul numpy pada python. Pertama kita import numpy dengan alias np.

Berikut adalah beberapa penulisan python di berbagai platform:

![alt text](https://drive.google.com/uc?id=1Vo7_qxBo3AGaKDtS1nym0Q-hq1Rxh2JH
)



Berikut contoh penulisan matriks pada python:

In [ ]:
A = np.array([[1, 2], [4, 5]])
A

array([[1, 2],
       [4, 5]])

In [ ]:
B = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# **Operasi Matriks Pada Python**

In [ ]:
P = np.array([[1, 2], [4, 5]])
P

array([[1, 2],
       [4, 5]])

In [ ]:
Q = np.array([[7, 8], [9, 10]])
Q

array([[ 7,  8],
       [ 9, 10]])

In [ ]:
a=29
a

29

**Penjumlahan Matriks**

In [ ]:
np.add(P,Q)

array([[ 8, 10],
       [13, 15]])

**Pengurangan Matriks**

In [ ]:
np.subtract(P,Q)

array([[-6, -6],
       [-5, -5]])

**Perkalian Skalar Matriks**

In [ ]:
a*P

array([[ 29,  58],
       [116, 145]])

**Perkalian Matriks**

In [ ]:
np.multiply(P,Q)

array([[ 7, 16],
       [36, 50]])

**Perkalian Titik Matriks (Dot Product)**

In [ ]:
np.dot(P,Q)

array([[25, 28],
       [73, 82]])

**Transpose Matriks**

In [ ]:
P.T

array([[1, 4],
       [2, 5]])

**Operasi Fungsi Pada Setiap Elemen Matriks - Akar Kuadrat**

In [ ]:
np.sqrt(P)

array([[1.        , 1.41421356],
       [2.        , 2.23606798]])

**Menjumlahkan Semua Elemen Kolom Sebuah Matriks**

In [ ]:
Q

array([[ 7,  8],
       [ 9, 10]])

In [ ]:
np.sum(Q,axis=1)

array([15, 19])

**Menjumlahkan Semua Elemen Baris Sebuah Matriks**

In [ ]:
np.sum(Q,axis=0)

array([16, 18])

# **Aljabar Linear Pada Python**

Dalam modul numpy juga disediakan fungsi-fungsi Aljabar Linear untuk matriks.
Beberapa konsep Aljabar Linear yang akan ditunjukkan di modul ini adalah
* Determinan
* Inverse
* Nilai eigen
* Vector eigen
* Matriks identitas
* Matriks satuan
* Matriks nol
* Matriks segitiga L dan U
* Dekomposisi L U matriks

In [ ]:
A = np.array([[2,3,4],[7, 8, 9],[10, 7, 8]])
A

array([[ 2,  3,  4],
       [ 7,  8,  9],
       [10,  7,  8]])

In [ ]:
B = np.array([[5,7,4],[6, 8, 9],[1, 2, 6]])
B

array([[5, 7, 4],
       [6, 8, 9],
       [1, 2, 6]])

**Determinan**


In [ ]:
np.linalg.det(A)

-20.000000000000007

**Inverse Matriks**

In [ ]:
np.linalg.inv(A)

array([[-0.05, -0.2 ,  0.25],
       [-1.7 ,  1.2 , -0.5 ],
       [ 1.55, -0.8 ,  0.25]])

**Nilai Eigen dan Vector Eigen**

In [ ]:
eig, vec_eig = np.linalg.eig(A)
print('Nilai eigen matriks A:')
print(eig)
print('Vektor eigen matriks A:')
print(vec_eig)

Nilai eigen matriks A:
[19.39079317 -1.9262474   0.53545423]
Vektor eigen matriks A:
[[-0.27295093 -0.54761756  0.15754422]
 [-0.6940728  -0.31621014 -0.8168342 ]
 [-0.66615369  0.7746781   0.55494297]]


**Matriks Identitas**

In [ ]:
Identitas=np.identity(5)
print(Identitas)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
Identitas[:,3]

array([0., 0., 0., 1., 0.])

**Matriks Satuan**

In [ ]:
Satuan=np.ones((2,3))
Satuan

array([[1., 1., 1.],
       [1., 1., 1.]])

**Matriks Nol**

In [ ]:
MatriksNol=np.zeros(10)
MatriksNol

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

**Matriks Segitiga Atas dan Bawah**

In [ ]:
M=np.array([[1,2,3],[4,5,6],[7,8,9]])
M

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
Lower=np.tril(M, -1)
Lower

array([[0, 0, 0],
       [4, 0, 0],
       [7, 8, 0]])

In [ ]:
Upper=np.triu(M, 1)
Upper

array([[0, 2, 3],
       [0, 0, 6],
       [0, 0, 0]])

**Matriks Dekomposisi LU**

In [ ]:
import numpy as np
import scipy.linalg as la
np.set_printoptions(suppress=True)

P, L, U = la.lu(A)
print(P)

print(L)

print(U)

[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]
[[1.         0.         0.        ]
 [0.7        1.         0.        ]
 [0.2        0.51612903 1.        ]]
[[10.          7.          8.        ]
 [ 0.          3.1         3.4       ]
 [ 0.          0.          0.64516129]]


# **Membangun Matriks Menggunakan Perulangan**

In [ ]:
C = np.arange(0,10,1)
C

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
C**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [ ]:
L = []
for i in C:
  L.append(i+1)
L

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
arr = []

A=np.zeros([3,4])
baris, kolom = np.shape(A)
print(baris)
print(kolom)
print(A)
arr=[]
for i in range(baris):
    arr.append([])
    print(arr)
    for j in range(kolom):
        arr[i].append((i+j)*2)
        print(arr)
print(np.array(arr))

3
4
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[]]
[[0]]
[[0, 2]]
[[0, 2, 4]]
[[0, 2, 4, 6]]
[[0, 2, 4, 6], []]
[[0, 2, 4, 6], [2]]
[[0, 2, 4, 6], [2, 4]]
[[0, 2, 4, 6], [2, 4, 6]]
[[0, 2, 4, 6], [2, 4, 6, 8]]
[[0, 2, 4, 6], [2, 4, 6, 8], []]
[[0, 2, 4, 6], [2, 4, 6, 8], [4]]
[[0, 2, 4, 6], [2, 4, 6, 8], [4, 6]]
[[0, 2, 4, 6], [2, 4, 6, 8], [4, 6, 8]]
[[0, 2, 4, 6], [2, 4, 6, 8], [4, 6, 8, 10]]
[[ 0  2  4  6]
 [ 2  4  6  8]
 [ 4  6  8 10]]
